export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  image: string
  category: string
}

const CDN = 'https://cdn.prod.website-files.com/680b491848812a8a8cf323ac'

export const BLOGS: BlogPost[] = [
  {
    slug: 'landscape-installation-and-maintenance',
    title: 'Landscape Installation and Maintenance: How to Plan Your Northern Virginia Outdoor Project',
    excerpt: 'Planning a landscape installation in Northern Virginia? Learn how installation and long-term maintenance work together to protect your investment.',
    image: '/blogs/blog-18-img-1.jpg',
    category: 'Design',
  },
  {
    slug: 'landscape-maintenance-near-me',
    title: 'Landscape Maintenance Near Me: How to Stop Cycling Through Crews Every Season',
    excerpt: 'Tired of finding new landscape maintenance near you every season? Learn what a long-term maintenance relationship looks like and how to find a crew worth keeping in Northern Virginia.',
    image: '/blogs/blog-17-img-1.jpg',
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'commercial-landscape-maintenance-near-me',
    title: 'Commercial Landscape Maintenance Near Me: How Property Managers Find a Reliable Partner',
    excerpt: 'Finding reliable commercial landscape maintenance near you in Northern Virginia? A property manager\'s guide to vetting vendors, scoping contracts, and setting standards.',
    image: '/blogs/blog-16-img-1.jpg',
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'landscape-design-services',
    title: 'Landscape Design Services: Everything You Need to Know Before You Hire',
    excerpt: 'What do landscape design services actually include? A buyer\'s guide for Northern Virginia homeowners on process, pricing, and finding a company worth trusting.',
    image: '/blogs/blog-15-img-1.jpg',
    category: 'Design',
  },
  {
    slug: 'residential-landscaping-services',
    title: "Residential Landscaping Services: What's Included, What to Expect, and What to Pay",
    excerpt: "What do residential landscaping services actually include? A complete guide for Northern Virginia homeowners covering scope, pricing, and how to choose the right company.",
    image: '/blogs/blog-14-img-1.jpg',
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'landscape-design-and-build',
    title: 'Landscape Design and Build: What the Process Really Looks Like (Start to Finish)',
    excerpt: 'What does a landscape design and build project actually look like from start to finish? A transparent, step-by-step guide for Northern Virginia homeowners.',
    image: '/blogs/blog-13-img-1.jpg',
    category: 'Design',
  },
  {
    slug: 'outdoor-living-spaces-northern-virginia',
    title: 'Outdoor Living Spaces in Northern Virginia: Design Ideas for Every Backyard',
    excerpt: 'Outdoor living design ideas for Northern Virginia homeowners. Patios, fire pits, outdoor kitchens, and more from Sunrise Landscape & Design.',
    image: '/blogs/blog-12-img-1.jpg',
    category: 'Inspiration',
  },
  {
    slug: 'landscape-design-near-me',
    title: 'How to Find a Landscape Design Company Near You (And Actually Trust Them)',
    excerpt: 'Looking for landscape design near me? Learn how to vet, hire, and trust a local landscaping company in Northern Virginia.',
    image: '/blogs/blog-11-img-1.jpg',
    category: 'Design',
  },
  {
    slug: 'fire-pit-installation',
    title: 'Fire Pit Installation: Design Ideas, Costs, and What to Know Before You Build',
    excerpt: 'Planning a fire pit installation in Northern Virginia? Design ideas, cost ranges, permit requirements, and what to ask your contractor. Guide from Sunrise Landscape & Design.',
    image: `${CDN}/6a19ff2f4cfe38415e587630_6a19febaab43f3d2c7dd8b62_blog-20-img-1.jpeg`,
    category: 'Hardscaping',
  },
  {
    slug: 'retaining-walls-northern-virginia',
    title: 'Retaining Walls in Northern Virginia: Design Options, Costs, and How to Hire the Right Contractor',
    excerpt: 'Planning a retaining wall in Northern Virginia? Design options, cost ranges, permit requirements in Fairfax and Loudoun, and how to hire the right contractor.',
    image: `${CDN}/6a19ff2cb58821b8c3058306_6a19feb2c713cc457df6db94_blog-19-img-1.jpeg`,
    category: 'Hardscaping',
  },
  {
    slug: 'landscape-maintenance-services',
    title: "Landscape Maintenance Services: What's Included and What to Expect",
    excerpt: 'Landscape maintenance services include mowing, pruning, mulching, and seasonal cleanup. Northern Virginia homeowners pay $1,800–$6,000/year on average.',
    image: `${CDN}/69ddbf9bc1497d8d5b25624f_photo-1720333135329-2abafa05f30c.jpeg`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'commercial-landscape-maintenance',
    title: "Commercial Landscape Maintenance: A Property Manager's Complete Guide",
    excerpt: "Commercial landscape maintenance boosts property values up to 15%. A property manager's guide to schedules, budgeting, contracts, and vendor selection.",
    image: `${CDN}/69ddbf9bc1497d8d5b256248_photo-1743178207584-4a0c1109975e.jpeg`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'backyard-landscape-design',
    title: 'Backyard Landscape Design Ideas for Every Budget',
    excerpt: 'Backyard landscape design projects recover 50–75% of costs at resale. Explore budget-friendly to premium backyard ideas for Northern Virginia homeowners.',
    image: `${CDN}/69ddc1c95270569eb5ee63e1_photo-1748795218723-d52cfcae9977.jpeg`,
    category: 'Inspiration',
  },
  {
    slug: 'hardscape-contractor-near-me',
    title: "How to Find the Right Hardscape Contractor Near You: A Homeowner's Guide",
    excerpt: 'Learn how to find a qualified hardscape contractor near you. Covers Virginia DPOR licensing, costs ($15–$75+/sq ft), vetting tips, and questions to ask.',
    image: `${CDN}/69ddc193f41269eff9edd30e_photo-1681371979570-af52da025d7b.jpeg`,
    category: 'Hardscaping',
  },
  {
    slug: 'residential-landscaping',
    title: 'Residential Landscaping: Everything You Need to Know Before Starting Your Project',
    excerpt: 'Residential landscaping increases home value by 10–12%. Learn costs, seasonal timing, DIY vs. pro tips, and ROI data for your Northern Virginia project.',
    image: `${CDN}/69ddc15fb8acdbe2a6ab44dd_photo-1737233523182-99e287258d58.jpeg`,
    category: 'Plants',
  },
  {
    slug: 'landscape-design-services-near-me',
    title: 'How to Choose the Best Landscape Design Services Near You',
    excerpt: 'Learn how to choose the best landscape design services near you. Northern Virginia homeowners spend $4,000–$20,000+ on design, per HomeAdvisor.',
    image: `${CDN}/69ddc12fad1183eaaf1bacb2_photo-1461280360983-bd93eaa5051b.jpeg`,
    category: 'Design',
  },
  {
    slug: 'residential-landscape-design',
    title: "Residential Landscape Design: A Complete Homeowner's Guide",
    excerpt: 'Residential landscape design boosts home values by 10–12%. This guide covers planning, plants, hardscaping, and maintenance for Northern Virginia homeowners.',
    image: `${CDN}/69ddc10012fbb3098b089d47_photo-1713789296574-0e56ecd53cbb.jpeg`,
    category: 'Design',
  },
  {
    slug: 'front-yard-landscape-design',
    title: 'Front Yard Landscape Design Ideas That Transform Your Curb Appeal',
    excerpt: 'Front yard landscape design ideas that boost curb appeal. Landscaping recovers 217% of costs at resale. 10 proven ideas for Northern Virginia homes.',
    image: `${CDN}/69ddbff33400c816bbf24691_photo-1713656275767-e8140c59acca.jpeg`,
    category: 'Inspiration',
  },
  {
    slug: 'commercial-landscape-design',
    title: 'Commercial Landscape Design: Creating Professional Outdoor Spaces That Impress',
    excerpt: 'Commercial landscape design boosts property values by up to 15%. Learn how professional outdoor spaces attract tenants and reduce costs in Northern Virginia.',
    image: `${CDN}/69ddbf9bc1497d8d5b256248_photo-1743178207584-4a0c1109975e.jpeg`,
    category: 'Design',
  },
  {
    slug: 'modern-landscape-design',
    title: 'Modern Landscape Design: Trends, Ideas and Inspiration for 2026',
    excerpt: 'Modern landscape design is reshaping outdoor spaces in 2026, with 67% of homeowners prioritizing low-maintenance yards. Explore trends, ideas, and inspiration.',
    image: `${CDN}/69ddbf510a5718a830f8a687_photo-1571192776145-9f563c1df686.jpeg`,
    category: 'Design',
  },
  {
    slug: 'northern-virginia-landscaping-planting-guide',
    title: 'Landscaping in Northern Virginia: What Grows Best and How to Plan Your Yard',
    excerpt: 'Learn what plants grow best in Northern Virginia, the local planting zone, and how landscape design principles like the rule of three create balanced outdoor spaces.',
    image: `${CDN}/69d4b40b3b47d3c48eb08dad_69b0447ea15f0f23528f775d_1a.png`,
    category: 'Plants',
  },
  {
    slug: 'when-to-mulch-in-northern-virginia-mulch-installation-guide',
    title: 'When to Mulch in Northern Virginia | Mulch Installation Guide',
    excerpt: 'Learn the best time to mulch in Northern Virginia, proper mulch depth using the 3-3-3 rule, seasonal timing, and average mulch installation costs.',
    image: `${CDN}/69d4b40a3b47d3c48eb08da4_6993a8e46e4800836cf5d43e_Screenshot%25202026-02-16%2520at%25203.31.32%25E2%2580%25AFPM.png`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'snow-plowing-vs-snow-removal-costs',
    title: 'Snow Plowing vs Snow Removal: Costs, Differences, and What to Expect',
    excerpt: 'Snow plowing and snow removal are often used interchangeably, but they are not the same service. This guide explains the differences, costs, and what to expect.',
    image: `${CDN}/69d4b40b3b47d3c48eb08db0_69838951980490c4f1894a66_Screenshot%25202026-02-04%2520at%252010.00.22%25E2%2580%25AFAM.png`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'landscape-lighting-costs-northern-virginia',
    title: 'Landscape Lighting Cost, Design Tips, and Trends Homeowners Should Know',
    excerpt: 'Outdoor landscape lighting improves safety, curb appeal, and how your space is used after dark. This guide explains costs, design rules, and current trends.',
    image: `${CDN}/69d4b40b3b47d3c48eb08db4_696fbe5c3431a271d8023a0b_Screenshot%25202026-01-20%2520at%25209.41.36%25E2%2580%25AFAM.png`,
    category: 'Design',
  },
  {
    slug: 'landscape-design-costs-northern-virginia',
    title: 'Landscape Design Costs, Tips, and Budgeting: What Homeowners Need to Know',
    excerpt: 'Wondering how much landscape design costs? This guide answers the most searched landscaping questions, including pricing, budgeting, and smart ways to design an outdoor space.',
    image: `${CDN}/69d4b40a3b47d3c48eb08da7_6966adb8cdca43b0f35462d3_L_STANHOPE_PATIO.jpeg`,
    category: 'Design',
  },
  {
    slug: 'what-is-dormant-turf-and-why-it-matters-in-northern-virginia',
    title: 'What Is Dormant Turf and Why It Matters in Northern Virginia',
    excerpt: 'Dormant turf may look inactive during winter, but proper care is critical for a healthy spring lawn. Learn how to protect dormant grass through freeze-thaw cycles.',
    image: `${CDN}/69d4b4111c85ee53cb7e0b14_694ec7294ec3f7d7d0373a7e_brown-patch1.webp`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'snow-and-ice-management',
    title: 'Snow and Ice Management',
    excerpt: 'Winter snow removal and ice management in Northern Virginia helps prevent freeze-thaw damage to driveways, walkways, and landscaping while improving safety during storms.',
    image: `${CDN}/69d4b4121c85ee53cb7e0b22_694340873e1a5194f526f623_snow%2520%25201.png`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'year-round-landscape-maintenance-northern-virginia',
    title: 'The Ultimate Guide to Year Round Landscape Maintenance in Northern Virginia',
    excerpt: 'Keeping a landscape healthy in Northern Virginia requires year-round care. This guide breaks down the essential tasks for spring, summer, fall, and winter.',
    image: `${CDN}/69d4b4121c85ee53cb7e0b39_6927392b3d126e9bf57bd01c_43.png`,
    category: 'Seasonal Maintenance',
  },
  {
    slug: 'winter-outdoor-space-cozy-escape',
    title: 'Get Your Outdoor Space Winter-Ready: Build the Perfect Cozy Escape',
    excerpt: 'Winter is the best time to prepare your outdoor space for cozy nights ahead. Discover how custom patios, fireplaces, and landscape upgrades transform your backyard.',
    image: `${CDN}/69d4b4121c85ee53cb7e0b27_69122d10096cc25a4665aeda_2.png`,
    category: 'Inspiration',
  },
  {
    slug: 'dont-wait-for-spring',
    title: "Don't Wait for Spring — Prepare Your Soil Now",
    excerpt: 'Winter is the perfect time to prepare your soil for spring. Testing and enriching your soil now uncovers nutrient gaps and gives your garden a strong foundation.',
    image: `${CDN}/69d4b4111c85ee53cb7e0b17_69092df049fab46e799daf66_soil.jpeg`,
    category: 'Fertilization',
  },
  {
    slug: 'how-to-build-a-retaining-wall',
    title: 'How to Build a Retaining Wall',
    excerpt: 'Thinking about building your own retaining wall? Learn what it really takes — from design and permits to compacting gravel and installing drainage.',
    image: `${CDN}/69d4b41a0a444162842c3a8c_6900f2ce2851bf671073e5e0_2.png`,
    category: 'Hardscaping',
  },
  {
    slug: 'why-fall-fertilization-matters-for-trees-and-shrubs',
    title: 'Why Fall Fertilization Matters for Trees and Shrubs',
    excerpt: 'Prepare your landscape for winter by fertilizing in fall. Learn how the right nutrients strengthen roots, promote resilience, and set the stage for a vibrant spring.',
    image: `${CDN}/69d4b41a0a444162842c3a7f_68f1626ee07bc9626b690c99_Your%2520next%2520outdoor%2520transformation%2520starts%2520here%2520(600%2520x%2520600%2520px)%2520(3).png`,
    category: 'Plants',
  },
  {
    slug: 'transform-your-backyard-into-a-paradise',
    title: 'Transform Your Backyard Into a Paradise',
    excerpt: 'Your backyard holds untapped potential. Learn how to transform a standard Northern Virginia yard into a custom-designed outdoor paradise.',
    image: `${CDN}/69d4b41a0a444162842c3a79_686da341aeccbe5c27b3487c_Untitled%2520design%25203.png`,
    category: 'Design',
  },
  {
    slug: 'top-10-plants-for-your-garden',
    title: 'Top 10 Plants for Your Garden',
    excerpt: 'The right plant selection makes all the difference. Here are 10 expert-recommended plants chosen for resilience, versatility, and year-round performance in Northern Virginia.',
    image: `${CDN}/69d4b41a0a444162842c3a85_686da2b678b6286cd952f2a3_Untitled%2520design%25205.png`,
    category: 'Inspiration',
  },
  {
    slug: 'creating-a-sustainable-garden',
    title: 'Creating a Sustainable Garden',
    excerpt: 'A sustainable garden balances aesthetics, ecology, and efficiency. Learn how Northern Virginia homeowners can reduce water use, build healthier soil, and support local wildlife.',
    image: `${CDN}/69d4b41a0a444162842c3a82_686da363830cc7e50f0f22af_Untitled%2520design%25206.png`,
    category: 'Plants',
  },
  {
    slug: 'hardscaping-enhancing-your-outdoor-space',
    title: 'Hardscaping: Enhancing Your Outdoor Space',
    excerpt: 'Hardscaping provides the form and function that make your landscape practical and beautiful. Learn how patios, retaining walls, walkways, and fire features transform your yard.',
    image: `${CDN}/69d4b41f96415742e93a6777_686da30842da4ed0afe9ab51_Untitled%2520design%25201.png`,
    category: 'Hardscaping',
  },
  {
    slug: 'the-benefits-of-native-plants',
    title: 'The Benefits of Native Plants',
    excerpt: 'Native plants are a game-changer for Northern Virginia homeowners. Learn how incorporating native species reduces maintenance, supports local wildlife, and creates resilient landscapes.',
    image: `${CDN}/69d4b41f96415742e93a677a_686da2c4384456aa49958a57_Untitled%2520design%25204.png`,
    category: 'Plants',
  },
  {
    slug: 'designing-with-color-in-mind',
    title: 'Designing with Color in Mind',
    excerpt: 'Color is a powerful but often underused tool in landscape design. Learn how to use color theory, plant bloom times, and seasonal foliage to create a garden that looks great year-round.',
    image: `${CDN}/69d4b41f96415742e93a677d_686da384aac3cb06698458cd_Untitled%2520design%25202.png`,
    category: 'Native',
  },
]

export function getBlogBySlug(slug: string): BlogPost | undefined {
  return BLOGS.find((b) => b.slug === slug)
}
